#ddev-generated
ahoyapi: v2
commands:
  version:
    usage: Show related environment variables
    cmd: |
      echo -e "\033[0;32m"
      set | grep -e ^PLATFORMSH_RECIPES_
      echo -e "\033[0m"

  maintenance503:set:
    usage: Set the needed environment variable
    cmd: |
      gum log --level info "Setting 503 flag on $(platform environment:info id)...."
      platform variable:create --yes --update --level=environment --inheritable=false --value=true env:PLATFORMSH_RECIPES_MAINTENANCE_503

  maintenance503:dbdump:
    usage: Dump the whole database
    cmd: ${PLATFORMSH_RECIPES_INSTALLDIR-.}/platformsh-recipes/scripts/commands/maintenance503-dbdump.sh "$@"

  maintenance503:dbdump:clear:
    usage: Remove all dumps created by this feature.
    cmd: |
      gum log --level info "Removing dump-*.sql on $(platform environment:info id)..."
      platform ssh "rm -fv \$PLATFORM_APP_DIR/.deploy/dump-*.sql"

  maintenance503:dbrestore:
    usage: Restore the whole database
    cmd: ${PLATFORMSH_RECIPES_INSTALLDIR-.}/platformsh-recipes/scripts/commands/maintenance503-dbrestore.sh "$@"

  maintenance503:clear:
    usage: Remove the needed environment variable and dump
    cmd: |
      gum log --level info "Clearing 503 flag on $(platform environment:info id)...."
      platform variable:delete --yes env:PLATFORMSH_RECIPES_MAINTENANCE_503
      gum log --level warn "Remember to clear dumps after checking all is ok."
      gum log --level warn "You can use the 'ahoy platform maintenance503:dbdump:clear'"

  log:php:
    usage: Get lines of /var/log/php.access.log with useful filters
    cmd: ${PLATFORMSH_RECIPES_INSTALLDIR-.}/platformsh-recipes/scripts/logs/php.sh "$@"

  log:php:rpm:
    usage: Get rpm out of /var/log/php.access.log
    cmd: ${PLATFORMSH_RECIPES_INSTALLDIR-.}/platformsh-recipes/scripts/logs/php-rpm.sh "$@"

  log:php:top:
    usage: Get a sorted list of php pages by time. (--mem to sort by memory usage)
    cmd: ${PLATFORMSH_RECIPES_INSTALLDIR-.}/platformsh-recipes/scripts/logs/php-top.sh "$@"

  log:access:
    usage: Get lines of /var/log/access.log with useful filters
    cmd: ${PLATFORMSH_RECIPES_INSTALLDIR-.}/platformsh-recipes/scripts/logs/access.sh "$@"

  log:access:rpm:
    usage: Get rpm out of /var/log/access.log
    cmd: ${PLATFORMSH_RECIPES_INSTALLDIR-.}/platformsh-recipes/scripts/logs/access-rpm.sh "$@"

  log:ipblock:
    usage: Block BAD IPs
    cmd: ${PLATFORMSH_RECIPES_INSTALLDIR-.}/platformsh-recipes/scripts/logs/ipblock.sh "$@"

  ipblock:list:
    usage: Show platform http access information on master
    cmd: platform httpaccess -e master

  ipblock:add:
    usage: Add IP to the block list
    cmd: ${PLATFORMSH_RECIPES_INSTALLDIR-.}/platformsh-recipes/scripts/commands/ipblock-add.sh "$@"

  ipblock:rm:
    usage: Remove IP from the block list
    cmd: ${PLATFORMSH_RECIPES_INSTALLDIR-.}/platformsh-recipes/scripts/commands/ipblock-remove.sh "$@"

