#!/bin/bash

PLATFORMSH_RECIPES_INSTALLDIR=.
source $PLATFORMSH_RECIPES_INSTALLDIR/scripts/platformsh/functions/conditional-run.sh
export PLATFORM_APP_DIR=.cache
export PLATFORM_CACHE_DIR=.cache
export PLATFORM_APPLICATION=eyJhY2Nlc3MiOiB7InNzaCI6ICJjb250cmlidXRvciJ9LCAiYWRkaXRpb25hbF9ob3N0cyI6IHt9LCAiYXBwX2RpciI6ICIvYXBwIiwgImJ1aWxkIjogeyJjYWNoZXMiOiB7fSwgImZsYXZvciI6ICJjb21wb3NlciJ9LCAiY29uZmlnX2lkIjogIjAyMWY5ZjA1NzEyOGRiNGEyN2RmMDhiN2EzYmM3YmU3OWEzN2VlMTYiLCAiY29udGFpbmVyX3Byb2ZpbGUiOiBudWxsLCAiY3JvbnMiOiB7ImRydXBhbCI6IHsiY29tbWFuZHMiOiB7InN0YXJ0IjogImNkIHdlYiA7IGRydXNoIGNvcmUtY3JvbiIsICJzdG9wIjogbnVsbH0sICJzaHV0ZG93bl90aW1lb3V0IjogbnVsbCwgInNwZWMiOiAiKi8xOSAqICogKiAqIiwgInRpbWVvdXQiOiA4NjQwMH19LCAiZGVwZW5kZW5jaWVzIjogeyJub2RlanMiOiB7Im4iOiAiKiJ9LCAicGhwIjogeyJjb21wb3Nlci9jb21wb3NlciI6ICJeMi4xIn19LCAiZGlzayI6IDI0NTc2LCAiZW5kcG9pbnRzIjogeyJodHRwIjogeyJwb3J0IjogODAsICJzY2hlbWUiOiAiaHR0cCJ9LCAicGhwIjogeyJwb3J0IjogODAsICJzY2hlbWUiOiAiaHR0cCJ9fSwgImZpcmV3YWxsIjogbnVsbCwgImhvb2tzIjogeyJidWlsZCI6ICIjIEV4aXQgdGhlIGhvb2sgb24gYW55IGZhaWx1cmVcbnNldCAtZVxuXG4jIEluc3RhbGwgdGhlIHZlcnNpb24gc3BlY2lmaWVkIGluIHRoZSAubnZtcmMgZmlsZVxubiBhdXRvXG5cbiMgUmVzZXQgdGhlIGxvY2F0aW9uIGhhc2ggdG8gcmVjb2duaXplIHRoZSBuZXdseSBpbnN0YWxsZWQgdmVyc2lvblxuaGFzaCAtciAgICAgICAgICBcblxuIyBCdWlsZCBjdXN0b20gdGhlbWVzXG5jb21wb3NlciBwcm9qZWN0LXNldHVwXG4iLCAiZGVwbG95IjogbnVsbCwgInBvc3RfZGVwbG95IjogbnVsbH0sICJpbnN0YW5jZV9jb3VudCI6IDEsICJpc19hY3Jvc3Nfc3VibW9kdWxlIjogZmFsc2UsICJtb3VudHMiOiB7Ii8uY29uc29sZSI6IHsic291cmNlIjogImxvY2FsIiwgInNvdXJjZV9wYXRoIjogImNvbnNvbGUifSwgIi8uZHJ1c2giOiB7InNvdXJjZSI6ICJsb2NhbCIsICJzb3VyY2VfcGF0aCI6ICJkcnVzaCJ9LCAiL2RydXNoLWJhY2t1cHMiOiB7InNvdXJjZSI6ICJsb2NhbCIsICJzb3VyY2VfcGF0aCI6ICJkcnVzaC1iYWNrdXBzIn0sICIvcHJpdmF0ZSI6IHsic291cmNlIjogImxvY2FsIiwgInNvdXJjZV9wYXRoIjogInByaXZhdGUifSwgIi90bXAiOiB7InNvdXJjZSI6ICJsb2NhbCIsICJzb3VyY2VfcGF0aCI6ICJ0bXAifSwgIi93ZWIvc2l0ZXMvZGVmYXVsdC9maWxlcyI6IHsic291cmNlIjogImxvY2FsIiwgInNvdXJjZV9wYXRoIjogImZpbGVzIn19LCAibmFtZSI6ICJkcnVwYWwiLCAib3BlcmF0aW9ucyI6IHt9LCAicHJlZmxpZ2h0IjogeyJlbmFibGVkIjogdHJ1ZSwgImlnbm9yZWRfcnVsZXMiOiBbXX0sICJyZWxhdGlvbnNoaXBzIjogeyJkYXRhYmFzZSI6IHsiZW5kcG9pbnQiOiAibXlzcWwiLCAic2VydmljZSI6ICJkYm15c3FsIn19LCAicmVzb3VyY2VzIjogbnVsbCwgInJ1bnRpbWUiOiB7ImV4dGVuc2lvbnMiOiBbInNvZGl1bSIsICJhcGN1IiwgImJsYWNrZmlyZSJdfSwgInNpemUiOiAiQVVUTyIsICJzbHVnX2lkIjogImN1ZXdjeGptN2p4a2MtZHJ1cGFsLThhYmM4ZTJiYWY4ZWZjYmRjZWYyNTY2NjhmZDdlM2IyZTE0NDg3ZjUtMDIxZjlmMDU3MTI4ZGI0YTI3ZGYwOGI3YTNiYzdiZTc5YTM3ZWUxNiIsICJzb3VyY2UiOiB7Im9wZXJhdGlvbnMiOiB7fSwgInJvb3QiOiAiLyJ9LCAic3RhY2siOiBbXSwgInRpbWV6b25lIjogbnVsbCwgInRyZWVfaWQiOiAiOGFiYzhlMmJhZjhlZmNiZGNlZjI1NjY2OGZkN2UzYjJlMTQ0ODdmNSIsICJ0eXBlIjogInBocDo4LjE6NzEwIiwgInZhcmlhYmxlcyI6IHsiZW52IjogeyJOX1BSRUZJWCI6ICIvYXBwLy5nbG9iYWwifX0sICJ3ZWIiOiB7ImxvY2F0aW9ucyI6IHsiLyI6IHsiYWxsb3ciOiBmYWxzZSwgImV4cGlyZXMiOiAiNW0iLCAiaGVhZGVycyI6IHt9LCAicGFzc3RocnUiOiAiL2luZGV4LnBocCIsICJyb290IjogIndlYiIsICJydWxlcyI6IHsiXFwuKGpwZT9nfHBuZ3xnaWZ8c3Znej98Y3NzfGpzfG1hcHxpY298Ym1wfGVvdHx3b2ZmMj98b3RmfHR0ZikkIjogeyJhbGxvdyI6IHRydWV9LCAiXi9yb2JvdHNcXC50eHQkIjogeyJhbGxvdyI6IHRydWV9LCAiXi9zaXRlbWFwXFwueG1sJCI6IHsiYWxsb3ciOiB0cnVlfSwgIl4vc2l0ZXMvW14vXSsvc2V0dGluZ3MuKj9cXC5waHAkIjogeyJzY3JpcHRzIjogZmFsc2V9LCAiXi9zaXRlcy9zaXRlc1xcLnBocCQiOiB7InNjcmlwdHMiOiBmYWxzZX19LCAic2NyaXB0cyI6IHRydWV9LCAiL3NpdGVzL2RlZmF1bHQvZmlsZXMiOiB7ImFsbG93IjogdHJ1ZSwgImV4cGlyZXMiOiAiNW0iLCAiaGVhZGVycyI6IHt9LCAicGFzc3RocnUiOiAiL2luZGV4LnBocCIsICJyb290IjogIndlYi9zaXRlcy9kZWZhdWx0L2ZpbGVzIiwgInJ1bGVzIjogeyJeL3NpdGVzL2RlZmF1bHQvZmlsZXMvKGNzc3xqcykiOiB7ImV4cGlyZXMiOiAiMncifX0sICJzY3JpcHRzIjogZmFsc2V9fSwgIm1vdmVfdG9fcm9vdCI6IGZhbHNlfX0=
export PLATFORMSH_RECIPES_VERBOSE=true

platformsh_recipes_cr_init "empty" "" -P /dev/null
platformsh_recipes_cr_success "empty"
platformsh_recipes_cr_init "cachethis" "" \
  cachethis/
if platformsh_recipes_cr_should_run "cachethis"; then
  echo "Should run"
  platformsh_recipes_cr_cache_store "cachethis" cachethis/
  platformsh_recipes_cr_success "cachethis"
else
  platformsh_recipes_cr_cache_restore "cachethis" cachethis/
fi

platformsh_recipes_cr_init "scripts" "" \
  scripts/
if platformsh_recipes_cr_should_run "scripts"; then
  platformsh_recipes_cr_cache_store "scripts" cachethis/
  platformsh_recipes_cr_success "scripts"
else
  platformsh_recipes_cr_cache_restore "scripts" cachethis/
fi

platformsh_recipes_cr_preset_drupal_composer

platformsh_recipes_cr_cache_cleanup

platformsh_recipes_cr_deploy_should_run "composer" && echo "do composer"
platformsh_recipes_cr_deploy_store
platformsh_recipes_cr_deploy_should_run "composer" || echo "do not composer"

# Errors
platformsh_recipes_cr_init "just one argument"
platformsh_recipes_cr_cache_store "cachethis"
platformsh_recipes_cr_get_cache_dir
platformsh_recipes_cr_should_run
platformsh_recipes_cr_success
{ PLATFORM_APP_DIR=/app platformsh_recipes_cr_deploy_store; }
